# Generated by Django 3.2.11 on 2022-01-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adverts', '0002_auto_20220118_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='advert',
            name='category',
        ),
        migrations.AddField(
            model_name='advert',
            name='category',
            field=models.ManyToManyField(to='Adverts.Category'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотров'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Категория'),
        ),
    ]
