# Generated by Django 3.2.11 on 2022-01-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adverts', '0003_auto_20220118_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.ManyToManyField(to='Adverts.Category', verbose_name='Категория'),
        ),
    ]
