# Generated by Django 3.2.11 on 2022-01-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adverts', '0004_alter_advert_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.ManyToManyField(to='Adverts.Category'),
        ),
    ]
