# Generated by Django 3.2.11 on 2022-01-20 02:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Adverts', '0005_alter_advert_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован?'),
        ),
        migrations.AddField(
            model_name='advert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.ManyToManyField(to='Adverts.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Adverts.city', verbose_name='Город'),
        ),
    ]
